# Based on https://github.com/simonw/ca-fires-history file .github/workflows/scrape.yml

name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest uwhnews.more-sport.com data
      run: |-
        curl 'https://uwhnews.more-sport.com/where-to-flick/' > uwhnews.more-sport.com.where-to-flick.html
    - name: Fetch latest belgiumuwh.be data
      run: |-
        curl 'https://www.belgiumuwh.be/clubs-in-belgium/' > belgiumuwh.be.clubs-in-belgium.html
    - name: Fetch latest cuga.org data
      run: |-
        curl 'http://cuga.org/en/where-and-when-uwh/' > cuga.org.en.where-and-when-uwh.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u +'%FT%TZ')
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
